# uncompyle6 version 3.9.3
# Python bytecode version base 2.7 (62211)
# Decompiled from: Python 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
# Embedded file name: ValkyrienBE/common/events.py
"""
跨端自定义事件名称常量
所有 Client ↔ Server 通信的事件名统一定义于此，杜绝硬编码字符串。
"""
C2S_PHYSIC_BLOCK = 'VBE_C2S_PhysicBlock'
C2S_PHYSIC_BLOCK_REGION = 'VBE_C2S_PhysicBlockRegion'
C2S_REMOVE_PHYSIC_BLOCK = 'VBE_C2S_RemovePhysicBlock'
C2S_CATCH_BLOCK = 'VBE_C2S_CatchBlock'
C2S_RELEASE_BLOCK = 'VBE_C2S_ReleaseBlock'
C2S_ROTATE_CAUGHT_BLOCK = 'VBE_C2S_RotateCaughtBlock'
C2S_SUCK_BLOCK = 'VBE_C2S_SuckBlock'
C2S_SPRAY_BLOCK = 'VBE_C2S_SprayBlock'
C2S_INIT_PHYS_BLOCKS = 'VBE_C2S_InitPhysBlocks'
C2S_DELETE_ALL_PHYS = 'VBE_C2S_DeleteAllPhys'
C2S_REQUEST_ENTITY_RENDER = 'VBE_C2S_RequestEntityRender'
C2S_PLACE_BLOCK_ON_SHIP = 'VBE_C2S_PlaceBlockOnShip'
C2S_DESTROY_BLOCK_ON_SHIP = 'VBE_C2S_DestroyBlockOnShip'
C2S_REFRESH_SHIP = 'VBE_C2S_RefreshShip'
C2S_EXIT_INTERACT = 'VBE_C2S_ExitInteract'
C2S_FALLBACK_BLOCK_CONFIRM = 'VBE_C2S_FallbackBlockConfirm'
S2C_RENDER_BLOCK = 'VBE_S2C_RenderBlock'
S2C_RENDER_BLOCK_BATCH = 'VBE_S2C_RenderBlockBatch'
S2C_ON_CATCH_BLOCK = 'VBE_S2C_OnCatchBlock'
S2C_ON_RELEASE_BLOCK = 'VBE_S2C_OnReleaseBlock'
S2C_ON_SPRAY_STATE_CHANGED = 'VBE_S2C_OnSprayStateChanged'
S2C_ON_ALL_DELETED = 'VBE_S2C_OnAllPhysDeleted'
S2C_CONFIRM_STATE = 'VBE_S2C_ConfirmState'
S2C_PLAY_SOUND_PARTICLE = 'VBE_S2C_PlaySoundParticle'
S2C_RESET_BUTTONS = 'VBE_S2C_ResetButtons'
S2C_FALLBACK_BLOCK_READY = 'VBE_S2C_FallbackBlockReady'
ALL_C2S_EVENTS = [
 C2S_PHYSIC_BLOCK, 
 C2S_PHYSIC_BLOCK_REGION, 
 C2S_REMOVE_PHYSIC_BLOCK, 
 C2S_CATCH_BLOCK, 
 C2S_RELEASE_BLOCK, 
 C2S_ROTATE_CAUGHT_BLOCK, 
 C2S_SUCK_BLOCK, 
 C2S_SPRAY_BLOCK, 
 C2S_INIT_PHYS_BLOCKS, 
 C2S_DELETE_ALL_PHYS, 
 C2S_REQUEST_ENTITY_RENDER, 
 C2S_PLACE_BLOCK_ON_SHIP, 
 C2S_DESTROY_BLOCK_ON_SHIP, 
 C2S_REFRESH_SHIP, 
 C2S_EXIT_INTERACT, 
 C2S_FALLBACK_BLOCK_CONFIRM]
ALL_S2C_EVENTS = [
 S2C_RENDER_BLOCK, 
 S2C_RENDER_BLOCK_BATCH, 
 S2C_ON_CATCH_BLOCK, 
 S2C_ON_RELEASE_BLOCK, 
 S2C_ON_SPRAY_STATE_CHANGED, 
 S2C_ON_ALL_DELETED, 
 S2C_CONFIRM_STATE, 
 S2C_PLAY_SOUND_PARTICLE, 
 S2C_RESET_BUTTONS, 
 S2C_FALLBACK_BLOCK_READY]

